#!/bin/bash

exercism download --track kotlin --exercise hello-world
exercism download --track kotlin --exercise acronym
exercism download --track kotlin --exercise armstrong-numbers
exercism download --track kotlin --exercise circular-buffer
exercism download --track kotlin --exercise crypto-square
exercism download --track kotlin --exercise custom-set
exercism download --track kotlin --exercise dnd-character
exercism download --track kotlin --exercise darts
exercism download --track kotlin --exercise difference-of-squares
exercism download --track kotlin --exercise gigasecond
exercism download --track kotlin --exercise hamming
exercism download --track kotlin --exercise leap
exercism download --track kotlin --exercise pangram
exercism download --track kotlin --exercise perfect-numbers
exercism download --track kotlin --exercise protein-translation
exercism download --track kotlin --exercise rna-transcription
exercism download --track kotlin --exercise raindrops
exercism download --track kotlin --exercise resistor-color
exercism download --track kotlin --exercise resistor-color-duo
exercism download --track kotlin --exercise resistor-color-trio
exercism download --track kotlin --exercise reverse-string
exercism download --track kotlin --exercise run-length-encoding
exercism download --track kotlin --exercise scale-generator
exercism download --track kotlin --exercise scrabble-score
exercism download --track kotlin --exercise secret-handshake
exercism download --track kotlin --exercise space-age
exercism download --track kotlin --exercise transpose
exercism download --track kotlin --exercise two-fer
exercism download --track kotlin --exercise yacht
exercism download --track kotlin --exercise affine-cipher
exercism download --track kotlin --exercise all-your-base
exercism download --track kotlin --exercise allergies
exercism download --track kotlin --exercise atbash-cipher
exercism download --track kotlin --exercise bank-account
exercism download --track kotlin --exercise beer-song
exercism download --track kotlin --exercise binary-search
exercism download --track kotlin --exercise binary-search-tree
exercism download --track kotlin --exercise bob
exercism download --track kotlin --exercise bowling
exercism download --track kotlin --exercise collatz-conjecture
exercism download --track kotlin --exercise diamond
exercism download --track kotlin --exercise etl
exercism download --track kotlin --exercise flatten-array
exercism download --track kotlin --exercise forth
exercism download --track kotlin --exercise grade-school
exercism download --track kotlin --exercise grains
exercism download --track kotlin --exercise isbn-verifier
exercism download --track kotlin --exercise isogram
exercism download --track kotlin --exercise kindergarten-garden
exercism download --track kotlin --exercise knapsack
exercism download --track kotlin --exercise largest-series-product
exercism download --track kotlin --exercise linked-list
exercism download --track kotlin --exercise luhn
exercism download --track kotlin --exercise matching-brackets
exercism download --track kotlin --exercise matrix
exercism download --track kotlin --exercise minesweeper
exercism download --track kotlin --exercise nth-prime
exercism download --track kotlin --exercise nucleotide-count
exercism download --track kotlin --exercise pascals-triangle
exercism download --track kotlin --exercise phone-number
exercism download --track kotlin --exercise pig-latin
exercism download --track kotlin --exercise prime-factors
exercism download --track kotlin --exercise rail-fence-cipher
exercism download --track kotlin --exercise robot-name
exercism download --track kotlin --exercise robot-simulator
exercism download --track kotlin --exercise roman-numerals
exercism download --track kotlin --exercise rotational-cipher
exercism download --track kotlin --exercise saddle-points
exercism download --track kotlin --exercise say
exercism download --track kotlin --exercise series
exercism download --track kotlin --exercise sieve
exercism download --track kotlin --exercise spiral-matrix
exercism download --track kotlin --exercise sum-of-multiples
exercism download --track kotlin --exercise triangle
exercism download --track kotlin --exercise word-count
exercism download --track kotlin --exercise wordy
exercism download --track kotlin --exercise anagram
exercism download --track kotlin --exercise change
exercism download --track kotlin --exercise clock
exercism download --track kotlin --exercise complex-numbers
exercism download --track kotlin --exercise diffie-hellman
exercism download --track kotlin --exercise dominoes
exercism download --track kotlin --exercise list-ops
exercism download --track kotlin --exercise meetup
exercism download --track kotlin --exercise react
exercism download --track kotlin --exercise simple-cipher
exercism download --track kotlin --exercise sublist
exercism download --track kotlin --exercise zebra-puzzle
